// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/daqing/airway/lib/utils"
)

// Registry renders the shared chrome of the web UI: header with brand and
// navigation, a centered content column, and the registry stylesheet.
// Pages compose their content inside it:
//
//	@layouts.Registry("Repositories") {
//		…page content…
//	}
func Registry(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t\t.registry { min-height: 100vh; background: var(--aw-bg); color: var(--aw-fg); font-family: var(--aw-font); }\n\t\t\t.registry a { color: var(--aw-primary); text-decoration: none; }\n\t\t\t.registry a:hover { text-decoration: underline; }\n\t\t\t.registry header {\n\t\t\t\tdisplay: flex; align-items: center; gap: 24px;\n\t\t\t\tpadding: 14px 24px; border-bottom: 1px solid var(--aw-border);\n\t\t\t}\n\t\t\t.registry .brand { font-size: 17px; font-weight: 650; color: var(--aw-fg); letter-spacing: -0.2px; }\n\t\t\t.registry .brand:hover { text-decoration: none; }\n\t\t\t.registry nav { display: flex; gap: 16px; font-size: 14px; }\n\t\t\t.registry nav a { color: var(--aw-muted); }\n\t\t\t.registry nav a:hover { color: var(--aw-fg); text-decoration: none; }\n\t\t\t.registry-main { width: min(960px, calc(100% - 48px)); margin: 0 auto; padding: 32px 0 64px; }\n\t\t\t.registry h1 { font-size: 24px; letter-spacing: -0.4px; margin: 0; }\n\t\t\t.registry .muted { color: var(--aw-muted); }\n\t\t\t.registry .section-head { display: flex; align-items: baseline; justify-content: space-between; margin: 32px 0 14px; }\n\t\t\t.registry .section-head h2 { font-size: 15px; margin: 0; }\n\t\t\t.registry code {\n\t\t\t\tfont-family: var(--aw-mono); font-size: 0.9em;\n\t\t\t\tbackground: var(--aw-surface); border: 1px solid var(--aw-border);\n\t\t\t\tborder-radius: var(--aw-radius-sm); padding: 1px 5px;\n\t\t\t}\n\t\t\t.registry .search { display: flex; gap: 10px; margin-top: 22px; max-width: 560px; }\n\t\t\t.registry .search input { flex: 1; }\n\t\t\t.registry .hero { padding: 24px 0 8px; }\n\t\t\t.registry .hero .muted { margin: 8px 0 0; }\n\t\t\t.registry table a { font-weight: 500; }\n\t\t\t.registry .aw-empty { margin: 40px 0; }\n\t\t</style> <div class=\"registry\"><header><a class=\"brand\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(utils.URLPrefix() + "/"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layouts/registry.templ`, Line: 48, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">Air Registry</a><nav><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(utils.URLPrefix() + "/repos"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layouts/registry.templ`, Line: 50, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">Repositories</a></nav></header><main class=\"registry-main\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(title).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
